config/routes.rb
Rails.application.routes.draw do


  # Edits current user's checkin so that they're checkout out per the Checkin/check_out action
  post("checkins/:id/check_out", { :controller => "checkins", :action => "check_out"})

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :requests

  resources :checkins

  resources :songs

  resources :reviews

  resources :performances

  resources :venues

  devise_for :users

  devise_scope :user do
    root "devise/registrations#edit"
  end

end

app/models/song.rb
class Song < ActiveRecord::Base
  mount_uploader :art, ArtUploader

  belongs_to :user
  # belongs_to :requester, :class_name => "User", :foreign_key => "requester_id"
  # belongs_to :requester, :class_name => "User"
  belongs_to :venue

  has_many :requests
  has_many :performances

  # validates :request, presence: true
  # validates :peformance, presence: true
  validates :artist, :presence => true
  validates :title, :presence => true
  validates :genre, :presence => true

  def venue
    Venue.find_by( :user_id => current_user.id )
  end

  def checkin
    Checkin.find_by( :user_id => current_user.id )
  end

end


# Song should belong to a requester (User)

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  before_action :stop_reg_user, only: [:update, :edit, :destroy, :new]

  def stop_reg_user
    if current_user.is_admin != true
      redirect_to :songs, notice: "Sorry. Only admin can do that."
    end
  end

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to :songs, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to :songs, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:artist, :title, :genre, :lyrics, :art, :user_id)
    end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.erb
<%= simple_form_for(@song) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :artist %>
    <%= f.input :art, required: false, hint: "Upload album or artist art" %>
    <%= f.hidden_field :art_cache %>
    <%= f.input :title %>
    <%= f.input :genre %>
    <%= f.input :lyrics %>
    <%#= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Edit Song #<%= @song.id %></h3>
      </div>
      <div class="panel-body">
        <%= render 'form', song: @song %>
      </div>
    </div>
  </div>
</div>

app/views/songs/index.html.erb
<div class="page-header">
  <h1>
    Songs
    <i class="fa fa-music fa-1x"></i><small> Find your song</small>
    <% if current_user.is_admin == true  %>
      <%= link_to icon('music'), new_song_path, class: "btn btn-lg btn-success" %>
    <% end %>

  </h1>
</div>

<!-- Responsive, Isotope-based layout example -->

<div class="row">
  <div class="col-xs-12">
    <input type="text" id="quicksearch" placeholder="Search Songs (start typing)" class="form-control">
  </div>
</div>

<hr>

<div class="row isotope-container">
<% @songs.each do |song| %>
  <div class="col-xs-12 col-sm-12 col-md-4 col-lg-3 isotope-item">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Song #<%= song.id %></h3>
      </div>
      <div class="panel-body">
        <dl>
          <dt>Artist</dt>
          <dd><%= song.artist %></dd>

          <dd><%= image_tag song.art, :height => '50px', :width => '50px', :class => 'img-square'  %></dd>

          <dt>Title</dt>
          <dd><%= song.title %></dd>

          <dt>Genre</dt>
          <dd><%= song.genre %></dd>

          <!-- <dt>Lyrics</dt> -->
          <dd><%#= song.lyrics %></dd>

          <!-- <dt>User</dt> -->
          <dd><%#= song.user %></dd>
        </dl>

        <div class="btn-group btn-group-justified">
          <%= link_to icon('play-circle'), song, class: "btn btn-primary" %>

          <%= link_to icon('edit'), edit_song_url(song), class: "btn btn-warning" %>

          <%= link_to icon('trash-o'), song, method: :delete, data: { confirm: "Do you really want to delete this song?" }, class: "btn btn-danger" %>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

<!-- JavaScript for Isotope layout and quicksearch -->
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/3.1.8/imagesloaded.pkgd.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.0.0/isotope.pkgd.min.js"></script>
<script>
  $(function() {
    // quick search regex
    var qsRegex;

    // init Isotope
    var $container = $('.isotope-container');

    $container.imagesLoaded(function() {
      $container.isotope({
        itemSelector: '.isotope-item',
        layoutMode: 'masonry',
        filter: function() {
          return qsRegex ? $(this).text().match( qsRegex ) : true;
        }
      })
    });

    // use value of search field to filter
    var $quicksearch = $('#quicksearch').keyup( debounce( function() {
      qsRegex = new RegExp( $quicksearch.val(), 'gi' );
      $container.isotope();
    }, 200 ) );

  });

  // debounce so filtering doesn't happen every millisecond
  function debounce( fn, threshold ) {
    var timeout;
    return function debounced() {
      if ( timeout ) {
        clearTimeout( timeout );
      }
      function delayed() {
        fn();
        timeout = null;
      }
      timeout = setTimeout( delayed, threshold || 100 );
    }
  }
</script>

<!-- End responsive, Isotope-based layout example -->

app/views/songs/new.html.erb
<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">New Song</h3>
      </div>
      <div class="panel-body">
        <%= render 'form', song: @song %>
      </div>
    </div>
  </div>
</div>

app/views/songs/show.html.erb
<!-- Responsive panel example-->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Your Selection: Song #<%= @song.id %></h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
            <dl class="dl-horizontal">
              <dt>Artist</dt>
              <dd><%= @song.artist %></dd>

              <dd><%= image_tag @song.art, :height => '200px', :width => '200px', :class => 'img-circle'  %></dd>

              <dt>Title</dt>
              <dd><%= @song.title %></dd>

              <dt>Genre</dt>
              <dd><%= @song.genre %></dd>

              <dt>Lyrics</dt>
              <dd><%= @song.lyrics %></dd>

            <hr>

            <div align="center">

            <% @hr = Request.where({:user_id => current_user.id, :has_requested => true}) %>
            <% if @hr.present? %>
            <%#= redirect_to :root, notice: "Hey...slow your roll Superstar! You can only make one request at-a-time between performances." %>

            <h1 align="center">"Ooops!"</h1>
            <p><%= current_user.stagename %>, looks like you currently have a song in the request queue. You have to wait for the dj to clear it from the queue <em>before<em> you can request another.</p>
              <p><%= link_to icon('thumbs-down'), '/', class: "btn btn-danger" %></p>

            <% else %>

            <strong align="center">Confirm your request for </strong>"<%= @song.title %>" by <%= @song.artist %>
              <p><%= link_to icon('thumbs-up'), new_request_path(:song_id => params[:id], :user_id => (current_user.id), :venue_id => (current_user.checkin.venue_id) ), class: "btn btn-success" %></p>

<!--               <strong align="center">Confirm your request for </strong><%= @song.title %> by <%#= @song.artist %>
              <%#= link_to icon('thumbs-up'), new_request_path(@song), class: "btn btn-success" %> -->

              <%#= link_to icon('edit'), edit_song_path(@song), class: "btn btn-warning" %>

              <%#= link_to icon('trash-o'), @song, method: :delete, data: { confirm: "Do you really want to delete this song?" }, class: "btn btn-danger" %>

              <%# end %>
                <%#= redirect_to :root, :notice, "My man...you can only make one request before the other's removed from the queue!" %>

            <% end %>

            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- End responsive panel example -->