config/routes.rb
Rails.application.routes.draw do


  # Edits current user's checkin so that they're checkout out per the Checkin/check_out action
  post("checkins/:id/check_out", { :controller => "checkins", :action => "check_out"})

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :requests

  resources :checkins

  resources :songs

  resources :reviews

  resources :performances

  resources :venues

  devise_for :users

  devise_scope :user do
    root "devise/registrations#edit"
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  before_action :stop_reg_user, only: [:index, :show]

  def stop_reg_user
    if current_user.is_admin != true
      redirect_to :back, notice: "Go to the Performance_Queue and click on a performance to leave a review."
    end
  end

  # GET /reviews
  # GET /reviews.json
  def index
     if current_user.present?
      @reviews = current_user.reviews
    else
      @reviews = Review.all
   end
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new(:performance_id => params[:performance_id])
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.find_by({ :performance_id => params[:performance_id] })


    # @r = Review.find_by({ :matched => '@review.batch.matched', :batch_id => '@review.batch.id' })
    # @review = Review.new(review_params)
    # @review.user = current_user

    @review = Review.new(review_params)
    @review.user = current_user

    respond_to do |format|
      if @review.save
        format.html { redirect_to :performances, notice: 'Review was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:headline, :content, :rating, :performance_id )
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= simple_form_for(@review) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :headline, maxlength: 36,  hint: "Create a short headline for this review." %>
    <%#= f.input :content, hint: "Add some content about the performance." %>
    <%= f.input :rating, collection: 1..5, hint: "Hint: '6' is off the hook; '1' is drop the mic...you shouldn't be holdin' it." %>
    <%#= f.input :user_id %>
    <%= f.hidden_field :performance_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Edit Review #<%= @review.id %></h3>
      </div>
      <div class="panel-body">
        <%= render 'form', review: @review %>
      </div>
    </div>
  </div>
</div>

app/views/reviews/index.html.erb
<div class="page-header">
  <h1>
    Reviews
    <i class="fa fa-pencil fa-1x"></i>
    <%#= link_to icon('plus'), new_review_path, class: "btn btn-lg btn-success" %>
  </h1>
</div>

<!-- Responsive, Isotope-based layout example -->

<div class="row">
  <!-- <div class="col-xs-12">
    <input type="text" id="quicksearch" placeholder="Search Reviews (start typing)" class="form-control">
  </div> -->
</div>

<!-- <hr> -->

<div class="row isotope-container">
<% @reviews.each do |review| %>
      <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 isotope-item">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Review #<%#= @performance.review_id %></h3>
          </div>
          <div class="panel-body">
            <dl>
              <dt>User</dt>
              <dd><%#= performance.review.user %></dd>

              <dt>Performance</dt>
              <dd><%#= review.performance %></dd>

            </dl>
            <div class="btn-group btn-group-justified">
              <%= link_to icon('search-plus'), review, class: "btn btn-primary" %>

              <%= link_to icon('edit'), edit_review_url(review), class: "btn btn-warning" %>

              <%= link_to icon('trash-o'), review, method: :delete, data: { confirm: "Do you really want to delete this review?" }, class: "btn btn-danger" %>
            </div>
          </div>
        </div>
      </div>
<% end %>
</div>

<!-- JavaScript for Isotope layout and quicksearch -->
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/3.1.8/imagesloaded.pkgd.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.0.0/isotope.pkgd.min.js"></script>
<script>
  $(function() {
    // quick search regex
    var qsRegex;

    // init Isotope
    var $container = $('.isotope-container');

    $container.imagesLoaded(function() {
      $container.isotope({
        itemSelector: '.isotope-item',
        layoutMode: 'masonry',
        filter: function() {
          return qsRegex ? $(this).text().match( qsRegex ) : true;
        }
      })
    });

    // use value of search field to filter
    var $quicksearch = $('#quicksearch').keyup( debounce( function() {
      qsRegex = new RegExp( $quicksearch.val(), 'gi' );
      $container.isotope();
    }, 200 ) );

  });

  // debounce so filtering doesn't happen every millisecond
  function debounce( fn, threshold ) {
    var timeout;
    return function debounced() {
      if ( timeout ) {
        clearTimeout( timeout );
      }
      function delayed() {
        fn();
        timeout = null;
      }
      timeout = setTimeout( delayed, threshold || 100 );
    }
  }
</script>

<!-- End responsive, Isotope-based layout example -->

app/views/reviews/new.html.erb
<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">New Review for performance # <%= @review.performance_id %></h3>
        <p>Reviewing <%= @review.performance.user.stagename.pluralize %> performance of <%= @review.performance.song.artist.pluralize %> "<%= @review.performance.song.title %>"</p>
      </div>
      <div class="panel-body">
        <%= render 'form', review: @review %>
      </div>
    </div>
  </div>
</div>

app/views/reviews/show.html.erb
<!-- Responsive panel example-->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Review #<%= @review.id %> from performance # <%= @review.performance.id %></h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
            <dl class="dl-horizontal">

              <dt>Performer</dt>
              <dd><%= @review.performance.user.stagename %></dd>

              <dt>Headline:</dt>
              <dd><%= @review.headline %></dd>

              <dt>Detail:</dt>
              <dd><%= @review.content %></dd>
              <br>
              <dd><%= @review.user.stagename %> gives the performance a <%= @review.rating %> out of 5</dd>

              <dd><%#= @review.performance %></dd>

            </dl>
            <div class="btn-group btn-group-justified">
              <%= link_to icon('chevron-left'), reviews_path, class: "btn btn-primary" %>

              <%= link_to icon('edit'), edit_review_path(@review), class: "btn btn-warning" %>

              <%= link_to icon('trash-o'), @review, method: :delete, data: { confirm: "Do you really want to delete this review?" }, class: "btn btn-danger" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- End responsive panel example -->