config/routes.rb
Rails.application.routes.draw do


  # Edits current user's checkin so that they're checkout out per the Checkin/check_out action
  post("checkins/:id/check_out", { :controller => "checkins", :action => "check_out"})

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :requests

  resources :checkins

  resources :songs

  resources :reviews

  resources :performances

  resources :venues

  devise_for :users

  devise_scope :user do
    root "devise/registrations#edit"
  end

end

app/models/checkin.rb
class Checkin < ActiveRecord::Base
  belongs_to :user
  belongs_to :venue

  has_many :requests

  validates :user, :presence => true
  validates :venue, :presence => true
end



# Near future, validate :user so there can be no duplicate user IDs in the same table
# Then we can send the "Check Out" function to the Destroy Method (??), to delete the
# record from the table, allowing the user to checkin to other locations. We'll have
# to see what best practices is on this...

app/controllers/checkins_controller.rb
class CheckinsController < InheritedResources::Base
  before_action :set_checkin, only: [:show, :edit, :update, :destroy ]

  before_action :stop_reg_user, only: [:show, :index, :edit, :update]

  def stop_reg_user
    if current_user.is_dj != true
      redirect_to :checkins, notice: "Sorry. Only the DJ has access to that!"
    end
  end

  def index
    if current_user.present?
        @checkins = current_user.checkins
    else
        @checkins = Checkin.all
    end
  end

  def new
    if current_user.is_checked_in == true
      redirect_to :back, notice: "It appears you're already checked in somewhere, friendo!"
    else
      @checkin = Checkin.new( venue_id: params[:venue_id], user_id: (current_user.id))
      @checkin.user = current_user
      @checkin.is_checked_in = true # Sets checkin.is_checked_in to "true"
      current_user.is_checked_in = true # Sets current user's is_checked_in to "true"
      current_user.save
      @checkin.save
      redirect_to :songs, notice: "Cool! You're all checked in. Time to pick a song and start warming up the pipes!"
    end
  end

  def check_out
    @checkin = Checkin.find_by(params[:id])
    @checkin.user = current_user
    @checkin.is_checked_in = false
    if current_user.is_checked_in == true
      current_user.is_checked_in = false
      current_user.save
    end
    @checkin.save
    redirect_to :back, notice: "You've just checked out. Real nice champ!"
  end

  def update
    respond_to do |format|
      if @checkin.update(checkin_params)
        @checkin.is_checked_in = false
        @checkin.save
        format.html { redirect_to @checkin, notice: 'checkin was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.

    def set_checkin
      @checkin = Checkin.find(params[:id])
    end

    def checkin_params
      params.require(:checkin).permit(:is_checked_in, :user_id, :venue_id)
    end

end

app/helpers/checkins_helper.rb
module CheckinsHelper
end

app/views/checkins/_form.html.erb
<%= simple_form_for(@checkin) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :is_checked_in %>
    <%= f.association :user %>
    <%= f.association :venue %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/checkins/edit.html.erb
<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Edit Checkin #<%= @checkin.id %></h3>
      </div>
      <div class="panel-body">
        <%= render 'form', checkin: @checkin %>
      </div>
    </div>
  </div>
</div>

app/views/checkins/index.html.erb
<div class="page-header">
  <h1>
    Youre Checkins
    <%= link_to icon('check'), new_checkin_path, class: "btn btn-lg btn-success" %>
  </h1>
  <dt>DJ's Venue
  <%#= current_user.venue.name %>: Venue.name goes here </dt>
</div>

<div class="row isotope-container">
<% @checkins.each do |checkin| %>
  <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 isotope-item">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Checkin #<%= checkin.id %></h3>
      </div>
      <div class="panel-body">
        <%# if checkin.is_checked_in == true %>
        <% if @checkins.present? %>

          <dl>
            <dt align="center"><%= checkin.user.stagename %></dt>
            <dd align="center"><%= image_tag checkin.user.avatar, height: '50px', width: '50px', :class => 'img-circle' %></dd>

            <dt>Venue</dt>
            <dd><%= checkin.venue.name %></dd>

            <!-- <dt>Checked In</dt>
            <dd><%= checkin.created_at %></dd> -->

            <!-- <dt>Checked Out</dt>
            <dd><%#= checkin.updated_at %></dd> -->

          </dl>

        <dt>Click below to checkout</dt>
        <div class="btn-group btn-group-justified">
          <%#= link_to icon('search-plus'), checkin, class: "btn btn-primary" %>


          <%= link_to icon('check'), edit_checkin_url(checkin), class: "btn btn-danger" %>

          <%#= link_to icon('trash-o'), checkin, method: :delete, data: { confirm: "Do you really want to delete this checkin?" }, class: "btn btn-danger" %>
        </div>

<!--         <%# elsif @checkins.present?! %>
        <p><%= checkin.user.stagename %> checked out of <%= checkin.venue.name %> on <%= checkin.updated_at %>!</p> <p>Go to "Find a Karaoke Bar and select the bar you're currently in, or about to hit up.</p> -->
        <% end %>
      </div>
    </div>
  </div>
<% end %>
</div>


<!-- JavaScript for Isotope layout and quicksearch -->
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/3.1.8/imagesloaded.pkgd.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.0.0/isotope.pkgd.min.js"></script>
<script>
  $(function() {
    // quick search regex
    var qsRegex;

    // init Isotope
    var $container = $('.isotope-container');

    $container.imagesLoaded(function() {
      $container.isotope({
        itemSelector: '.isotope-item',
        layoutMode: 'masonry',
        filter: function() {
          return qsRegex ? $(this).text().match( qsRegex ) : true;
        }
      })
    });

    // use value of search field to filter
    var $quicksearch = $('#quicksearch').keyup( debounce( function() {
      qsRegex = new RegExp( $quicksearch.val(), 'gi' );
      $container.isotope();
    }, 200 ) );

  });

  // debounce so filtering doesn't happen every millisecond
  function debounce( fn, threshold ) {
    var timeout;
    return function debounced() {
      if ( timeout ) {
        clearTimeout( timeout );
      }
      function delayed() {
        fn();
        timeout = null;
      }
      timeout = setTimeout( delayed, threshold || 100 );
    }
  }
</script>

<!-- End responsive, Isotope-based layout example -->

app/views/checkins/new.html.erb
<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">New Checkin</h3>
      </div>
      <div class="panel-body">
        <%= render 'form', checkin: @checkin %>
      </div>
    </div>
  </div>
</div>

app/views/checkins/show.html.erb
<!-- Responsive panel example-->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Checkin #<%= @checkin.id %></h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
            <dl class="dl-horizontal">
              <dt>Is checked in</dt>
              <dd><%= @checkin.is_checked_in %></dd>

              <dt>User</dt>
              <dd><%= @checkin.user.stagename %></dd>

                <dd>
                  <div class="inline-rating">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                  </div>
                </dd>

              <dt>Venue</dt>
              <dd><%= @checkin.venue.name %></dd>

            </dl>
            <div class="btn-group btn-group-justified">
              <%= link_to icon('chevron-left'), checkins_path, class: "btn btn-primary" %>
              <%= link_to icon('stop'), edit_checkin_path(@checkin), class: "btn btn-danger" %></dd>
              <%#= link_to icon('edit'), edit_checkin_path(@checkin), class: "btn btn-warning" %>
              <%#= link_to icon('trash-o'), @checkin, method: :delete, data: { confirm: "Do you really want to delete this checkin?" }, class: "btn btn-danger" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- End responsive panel example -->