config/routes.rb
Rails.application.routes.draw do


  # Edits current user's checkin so that they're checkout out per the Checkin/check_out action
  post("checkins/:id/check_out", { :controller => "checkins", :action => "check_out"})

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :requests

  resources :checkins

  resources :songs

  resources :reviews

  resources :performances

  resources :venues

  devise_for :users

  devise_scope :user do
    root "devise/registrations#edit"
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shareaokev2!</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Shareaoke_BETA", root_url, :class => "navbar-brand" %>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
          <ul class="nav navbar-nav">
            <li><%= link_to "Find A Karaoke Bar", venues_path %></li>
            <li><%= link_to "Search Songs", songs_path %></li>
            <li><%= link_to "Performance Queue", performances_path %></li>
            <li><%= link_to "Reviews", reviews_path %></li>
          <% if current_user.present? %>
            <% if current_user.is_dj == true %>
              <li><%= link_to "Checkins/Outs", checkins_path %></li>
              <li><%= link_to "Requests", requests_path %></li>
            <% end %>
          <% end %>

          <ul class="nav navbar-nav navbar-center">
            <li>
              <a href="http://twitter.com">
                <!-- <span class="fa-stack fa-sm"> -->
                  <!-- <i class="fa fa-square-o fa-stack-2x"></i> -->
                  <i class="fa fa-twitter fa-stack-1x"></i>
                <!-- </span> -->
              </a>
            </li>
            <li>
              <a href="http://facebook.com">
              <!-- <span class="fa-stack fa-sm"> -->
                <!-- <i class="fa fa-square-o fa-stack-2x"></i> -->
                <i class="fa fa-facebook fa-stack-1x"></i>
              <!-- </span> -->
              </a>
            </li>
            <li>
              <a href="http://instagram.com">
                <!-- <span class="fa-stack fa-sm"> -->
                  <!-- <i class="fa fa-square-o fa-stack-2x"></i> -->
                  <i class="fa fa-instagram fa-stack-1x"></i>
                <!-- </span> -->
              </a>
            </li>
<!--             <li>
              <a href="http://yelp.com"> -->
              <!-- <span class="fa-stack fa-sm"> -->
                <!-- <i class="fa fa-square-o fa-stack-2x"></i> -->
                <!-- <i class="fa fa-yelp fa-stack-1x"></i> -->
              <!-- </span> -->
<!--               </a>
            </li> -->
            <li>
              <a href="http://plus.google.com">
              <!-- <span class="fa-stack fa-sm"> -->
                <!-- <i class="fa fa-square-o fa-stack-2x"></i> -->
                <i class="fa fa-google-plus fa-stack-1x"></i>
              <!-- </span> -->
              </a>
            </li>
            <li>
              <a href="#">
              <!-- <span class="fa-stack fa-sm"> -->
                <!-- <i class="fa fa-square-o fa-stack-2x"></i> -->
                <!-- <i class="fa fa-share-alt-square fa-stack-1x"></i> -->
              <!-- </span> -->
              </a>
            </li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to current_user.stagename, edit_user_registration_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, :method => "delete" %></li>
            <% else %>
              <li><%= link_to "Sign_up", new_user_registration_path %></li>
              <li><%= link_to "Log In", new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      <% if alert.present? %>
          <div class="alert alert-warning alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <%= alert %>
          </div>
        <% end %>

      <% if notice.present? %>
          <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <%= notice %>
          </div>
    <% end %>
      <%= yield %>
    </div>

  </body>
</html>